In [29]:
import numpy as np

# Create vectors
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# Addition and Subtraction
print(a + b)              # [11 22 33 44 55]
print(np.add(a, b))       # Same as above
print(a - b)              # [-9 -18 -27 -36 -45]

# Multiplication and Division
print(a * b)              # [10 40 90 160 250]
print(b / a)              # [10. 10. 10. 10. 10.]

# Power and Modulo
print(a ** 2)             # [ 1  4  9 16 25]
print(b % a)              # [0 0 0 0 0]

# Floor Division
print(b // a)             # [10 10 10 10 10]


[11 22 33 44 55]
[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 1  4  9 16 25]
[0 0 0 0 0]
[10 10 10 10 10]


In [30]:
# Broadcasting scalar operations
vector = np.array([1, 2, 3])

result = vector + 5       # [6 7 8]
result = vector * 2       # [2 4 6]
result = vector ** 3      # [1 8 27]
result = vector // 2     # [0 1 1]

In [31]:
# 1D vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

dot_prod = np.dot(v1, v2)        # 32 (1*4 + 2*5 + 3*6)
dot_prod = np.inner(v1, v2)      # Same result
dot_prod = v1 @ v2               # Modern syntax

# 2D array dot product
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
result = np.dot(m1, m2)
# Output: [[19 22]
#          [43 50]]


In [32]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

cross_prod = np.cross(v1, v2)
# Output: [-3  6 -3]

# Magnitude of cross product = area of parallelogram
magnitude = np.linalg.norm(cross_prod)


In [33]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

outer = np.outer(v1, v2)
# Output: [[ 4  5  6]
#          [ 8 10 12]
#          [12 15 18]]

outer = np.tensordot(v1, v2, axes=0)  # Alternative



In [34]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

product = np.dot(A, B)     # or A @ B
# Output: [[19 22]
#          [43 50]]

# Matrix-Vector multiplication
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([1, 2, 3])
result = matrix @ vector    # [14 32]

# Matrix power
result = np.linalg.matrix_power(A, 2)
# Output: [[19 22]

In [35]:
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

# Basic trigonometric
sin_vals = np.sin(angles)
cos_vals = np.cos(angles)
tan_vals = np.tan(angles)

# Hyperbolic
sinh_vals = np.sinh(angles)
cosh_vals = np.cosh(angles)
tanh_vals = np.tanh(angles)

# Inverse functions
arcsin = np.arcsin([0, 0.5, 1])
arccos = np.arccos([0, 0.5, 1])
arctan = np.arctan([0, 1])


In [36]:
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

# Basic trigonometric
sin_vals = np.sin(angles)
cos_vals = np.cos(angles)
tan_vals = np.tan(angles)

# Hyperbolic
sinh_vals = np.sinh(angles)
cosh_vals = np.cosh(angles)
tanh_vals = np.tanh(angles)

# Inverse functions
arcsin = np.arcsin([0, 0.5, 1])
arccos = np.arccos([0, 0.5, 1])
arctan = np.arctan([0, 1])
arctan2 = np.arctan2([1, 0], [0, 1])  # y, x

In [37]:
x = np.array([1, 2, 3, 4, 5])

# Exponential
exp_vals = np.exp(x)        # e^x
exp2_vals = np.exp2(x)      # 2^x
expm1_vals = np.expm1(x)    # e^x - 1

# Logarithmic
log_vals = np.log(x)        # Natural log
log10_vals = np.log10(x)    # Base 10
log2_vals = np.log2(x)      # Base 2
log1p_vals = np.log1p(x)    # log(1 + x)


In [38]:
x = np.array([1, 4, 9, 16, 25])

# Square and Cube root
sqrt_vals = np.sqrt(x)      # [1 2 3 4 5]
cbrt_vals = np.cbrt(x)      # Cube root

# Power
power_vals = np.power(x, 0.5)  # x^0.5 (same as sqrt)

# Absolute value
arr = np.array([-1, -2.5, 3, -4.7])
abs_vals = np.abs(arr)      # [1. 2.5 3. 4.7]


In [39]:
data = np.array([10, 20, 30, 40, 50])

# Sum and Product
total = np.sum(data)        # 150
product = np.prod(data)     # 12000000

# Mean, Median, Mode
mean_val = np.mean(data)    # 30.0
median_val = np.median(data)  # 30.0

# Min and Max
min_val = np.min(data)      # 10
max_val = np.max(data)      # 50


In [40]:
# Standard Deviation and Variance
std_dev = np.std(data)      # 14.14...
variance = np.var(data)     # 200.0

# Percentiles and Quantiles
p25 = np.percentile(data, 25)  # 25th percentile
p75 = np.percentile(data, 75)  # 75th percentile

# Cumulative Operations
cumsum = np.cumsum(data)    # [10 30 60 100 150]
cumprod = np.cumprod(data)  # [10 200 6000 ...]


In [41]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Operations along axes
row_sum = np.sum(matrix, axis=1)  # Sum each row: [6, 15, 24]
col_sum = np.sum(matrix, axis=0)  # Sum each col: [12, 15, 18]

row_mean = np.mean(matrix, axis=1)
col_max = np.max(matrix, axis=0)

# Multiple axes
total = np.sum(matrix, axis=(0, 1))  # Sum all elements


In [42]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# Comparison (returns boolean arrays)
result = a > b              # [F F F T T]
result = a < b              # [T T F F F]
result = a == b             # [F F T F F]
result = a != b             # [T T F T T]
result = a >= b             # [F F T T T]
result = a <= b             # [T T T F F]

# Using comparison functions
result = np.greater(a, b)
result = np.less(a, b)
result = np.equal(a, b)
result = np.not_equal(a, b)

In [43]:
x = np.array([True, True, False, False])
y = np.array([True, False, True, False])

# Logical operations
and_result = np.logical_and(x, y)  # [T F F F]
or_result = np.logical_or(x, y)   # [T T T F]
not_result = np.logical_not(x)    # [F F T T]

# Bitwise operations for boolean arrays
bitwise_and = x & y                # [T F F F]
bitwise_or = x | y                 # [T T T F]
bitwise_xor = x ^ y                # [F T T F]


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Filter using boolean condition
mask = arr > 5
filtered = arr[mask]        # [6 7 8 9 10]

# Multi-condition filtering
filtered = arr[(arr > 3) & (arr < 8)]  # [4 5 6 7]

# Using where()
result = np.where(arr > 5, arr**2, 0)
# Output: [0, 0, 0, 0, 0, 36, 49, 64, 81, 100]


In [45]:
arr = np.arange(12)

# Reshape to different dimensions
reshaped = arr.reshape(3, 4)
reshaped = arr.reshape(2, 2, 3)
reshaped = arr.reshape(-1)      # Flatten (infer dimension)

# Flatten and Ravel
flattened = arr.reshape(3, 4).flatten()  # Returns copy
raveled = arr.reshape(3, 4).ravel()      # Returns view if possible


In [46]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

transposed = matrix.T
# Output: [[1 4]
#          [2 5]
#          [3 6]]

# Multi-dimensional transpose
arr_3d = np.arange(24).reshape(2, 3, 4)
perm_arr = np.transpose(arr_3d, (1, 0, 2))


In [47]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Concatenate along axis
concat_axis0 = np.concatenate([a, b], axis=0)  # Vertical
concat_axis1 = np.concatenate([a, b], axis=1)  # Horizontal

# Stack (new axis)
stacked = np.stack([a, b], axis=0)

# vstack and hstack
v_stacked = np.vstack([a, b])
h_stacked = np.hstack([a, b])

# dstack (along depth)
d_stacked = np.dstack([a, b])


In [48]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Split along axes
split_v = np.vsplit(matrix, 3)  # Split vertically into 3
split_h = np.hsplit(matrix, 2)  # Split horizontally into 2

# Manual split
result = np.split(matrix, 2, axis=1)


In [49]:
arr = np.array([1, 2, 3])

# Add new axis
expanded = np.expand_dims(arr, axis=0)      # Shape: (1, 3)
expanded = np.expand_dims(arr, axis=1)      # Shape: (3, 1)

# Remove axes of size 1
arr_with_extra = arr.reshape(1, 3, 1)
squeezed = np.squeeze(arr_with_extra)       # Shape: (3,)


In [50]:
values = np.array([3.1, 3.5, 4.5, 2.9, -3.1, -3.5, -5.9])

# Round to nearest
rounded = np.round(values)              # [3. 4. 4. 3. -3. -4. -6.]

# Floor (round down)
floored = np.floor(values)              # [3. 3. 4. 2. -4. -4. -6.]

# Ceil (round up)
ceiled = np.ceil(values)                # [4. 4. 5. 3. -3. -3. -5.]

# Truncate (remove decimal)
truncated = np.trunc(values)            # [3. 3. 4. 2. -3. -3. -5.]

# Round to N decimals
rounded_2dec = np.round(values, 2)


In [51]:
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Determinant
det = np.linalg.det(A)

# Rank
rank = np.linalg.matrix_rank(A)


In [52]:
A = np.array([[1, 2], [3, 4]])

# Matrix inverse (only for square, non-singular matrices)
A_inv = np.linalg.inv(A)
# Verify: A @ A_inv ≈ I

# Pseudo-inverse (works for any matrix)
A_pinv = np.linalg.pinv(A)



In [53]:
A = np.array([[1, 2], [2, 1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

# For symmetric matrices
eigenvalues_sym, eigenvectors_sym = np.linalg.eigh(A)


In [54]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Singular Value Decomposition
U, S, VT = np.linalg.svd(A)

# QR Factorization
Q, R = np.linalg.qr(A)

# Cholesky Decomposition (for positive definite)
# L = np.linalg.cholesky(A)


In [55]:
# Solve Ax = b
A = np.array([[3, 2], [1, 2]])
b = np.array([1, 2])
x = np.linalg.solve(A, b)

# Least squares (overdetermined system)
A = np.array([[1, 0], [1, 1], [1, 2]])
b = np.array([6, 0, 0])
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)


In [56]:
# Broadcasting rules:
# 1. Arrays must have compatible dimensions
# 2. Dimensions are compatible if they're equal or one is 1

# Example 1: Vector + Scalar
a = np.array([1, 2, 3])
result = a + 5              # Broadcasts scalar to [5, 5, 5]

# Example 2: Different shapes
a = np.array([1, 2, 3])    # Shape: (3,)
b = np.array([[1], [2], [3]])  # Shape: (3, 1)
result = a + b              # Broadcasts to (3, 3)
# Output: [[2, 3, 4],
#          [3, 4, 5],
#          [4, 5, 6]]

# Example 3: Matrix operations
matrix = np.arange(12).reshape(3, 4)  # Shape: (3, 4)
vector = np.array([1, 2, 3, 4])       # Shape: (4,)
result = matrix + vector                # Broadcasts vector to each row


In [57]:
# Range-like functions
arr = np.arange(0, 10, 2)       # [0 2 4 6 8]
arr = np.linspace(0, 1, 5)      # [0. 0.25 0.5 0.75 1.]
arr = np.logspace(0, 2, 5)      # Logarithmically spaced

# Filled arrays
arr = np.zeros((2, 3))          # All zeros
arr = np.ones((3, 2))           # All ones
arr = np.full((2, 2), 7)        # Filled with 7
arr = np.empty((2, 3))          # Uninitialized

# Special matrices
eye = np.eye(3)                 # Identity matrix
diag = np.diag([1, 2, 3])       # Diagonal matrix

# Like functions (same shape as another array)
arr1 = np.zeros_like(arr)
arr2 = np.ones_like(arr)


In [58]:
# Modern approach (NumPy 1.17+)
rng = np.random.default_rng(seed=42)

# Uniform random [0, 1)
random_uniform = rng.random(5)

# Random integers
random_ints = rng.integers(0, 10, size=5)

# Distributions
normal = rng.normal(loc=0, scale=1, size=5)
binomial = rng.binomial(n=10, p=0.5, size=5)
poisson = rng.poisson(lam=3, size=5)
uniform = rng.uniform(low=0, high=1, size=5)

# Choice and shuffle
choices = rng.choice([1, 2, 3, 4, 5], size=3, replace=False)
arr = np.arange(10)
rng.shuffle(arr)

# Permutation
perm = rng.permutation(arr)


In [59]:
import time

n = 1000000

# ❌ Slow: Python Loop
start = time.time()
result_list = [x**2 for x in range(n)]
loop_time = time.time() - start

# ✅ Fast: NumPy Vectorized
arr = np.arange(n)
start = time.time()
result_array = arr**2
numpy_time = time.time() - start

print(f"Loop time: {loop_time:.4f}s")
print(f"NumPy time: {numpy_time:.4f}s")
print(f"Speedup: {loop_time/numpy_time:.1f}x")
# Typically 10-100x faster!


Loop time: 0.1042s
NumPy time: 0.0020s
Speedup: 51.7x
